// Sample device data for testing the dashboard
// This can be used to mock API responses during development

export const sampleDevices = [
  {
    id: '1',
    type: 'door_lock',
    name: 'Front Door Lock',
    location: 'Front Entrance',
    status: 'locked',
    locked: true,
    online: true,
    battery: 95,
    hasCamera: true,
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '2',
    type: 'door_lock',
    name: 'Back Door Lock',
    location: 'Back Entrance',
    status: 'unlocked',
    locked: false,
    online: true,
    battery: 78,
    hasCamera: false,
    lastUpdated: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: '3',
    type: 'light',
    name: 'Living Room Light',
    location: 'Living Room',
    status: 'on',
    brightness: 80,
    online: true,
    power: 8,
    lastUpdated: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: '4',
    type: 'light',
    name: 'Bedroom Light',
    location: 'Master Bedroom',
    status: 'off',
    brightness: 0,
    online: true,
    power: 0,
    lastUpdated: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: '5',
    type: 'light',
    name: 'Kitchen Light',
    location: 'Kitchen',
    status: 'on',
    brightness: 100,
    online: true,
    power: 10,
    lastUpdated: new Date(Date.now() - 300000).toISOString(),
  },
  {
    id: '6',
    type: 'plug',
    name: 'Coffee Maker',
    location: 'Kitchen',
    status: 'on',
    online: true,
    power: 1200,
    dailyUsage: '2.4',
    monthlyCost: '12.50',
    lastUpdated: new Date(Date.now() - 900000).toISOString(),
  },
  {
    id: '7',
    type: 'plug',
    name: 'TV',
    location: 'Living Room',
    status: 'on',
    online: true,
    power: 150,
    dailyUsage: '3.6',
    monthlyCost: '18.75',
    lastUpdated: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: '8',
    type: 'plug',
    name: 'Desk Lamp',
    location: 'Office',
    status: 'off',
    online: true,
    power: 0,
    dailyUsage: '0.8',
    monthlyCost: '4.20',
    lastUpdated: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: '9',
    type: 'motion',
    name: 'Hallway Sensor',
    location: 'Hallway',
    status: 'active',
    motionDetected: true,
    online: true,
    sensitivity: 'Medium',
    todayEvents: 24,
    lastMotion: new Date(Date.now() - 120000).toISOString(),
    lastUpdated: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: '10',
    type: 'motion',
    name: 'Garage Sensor',
    location: 'Garage',
    status: 'inactive',
    motionDetected: false,
    online: true,
    sensitivity: 'High',
    todayEvents: 8,
    lastMotion: new Date(Date.now() - 3600000).toISOString(),
    lastUpdated: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: '11',
    type: 'camera',
    name: 'Front Door Camera',
    location: 'Front Entrance',
    online: true,
    resolution: '1080p',
    lastUpdated: new Date().toISOString(),
  },
  {
    id: '12',
    type: 'camera',
    name: 'Backyard Camera',
    location: 'Backyard',
    online: true,
    resolution: '720p',
    lastUpdated: new Date().toISOString(),
  },
];

export const sampleLogs = [
  {
    type: 'door_lock',
    message: 'Front Door Lock was unlocked',
    action: 'unlock',
    deviceName: 'Front Door Lock',
    device: 'Front Door Lock',
    location: 'Front Entrance',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    details: 'Unlocked by mobile app',
  },
  {
    type: 'motion',
    message: 'Motion detected in Hallway',
    action: 'motion_detected',
    deviceName: 'Hallway Sensor',
    device: 'Hallway Sensor',
    location: 'Hallway',
    timestamp: new Date(Date.now() - 600000).toISOString(),
    details: 'Motion sensor triggered',
  },
  {
    type: 'light',
    message: 'Living Room Light turned on',
    action: 'turned_on',
    deviceName: 'Living Room Light',
    device: 'Living Room Light',
    location: 'Living Room',
    timestamp: new Date(Date.now() - 900000).toISOString(),
    details: 'Brightness set to 80%',
  },
  {
    type: 'plug',
    message: 'Coffee Maker turned on',
    action: 'turned_on',
    deviceName: 'Coffee Maker',
    device: 'Coffee Maker',
    location: 'Kitchen',
    timestamp: new Date(Date.now() - 1200000).toISOString(),
    details: 'Power consumption: 1200W',
  },
  {
    type: 'door_lock',
    message: 'Back Door Lock was locked',
    action: 'lock',
    deviceName: 'Back Door Lock',
    device: 'Back Door Lock',
    location: 'Back Entrance',
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    details: 'Auto-locked after 5 minutes',
  },
];

export const sampleUser = {
  id: '1',
  name: 'John Doe',
  email: 'john@example.com',
  role: 'owner',
};

// Mock login credentials for testing
export const testCredentials = {
  email: 'admin@smarthome.com',
  password: 'admin123',
};
